// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ModularVariableCheck
{
    using UnityEngine;
    
    
    public sealed class VariableTest_Lessthan2_MVC : ModularCheckBase
    {
        
        public VariableTester scriptObjectRef;
        
        private float testAgainst = 6F;
        
        public override bool Check()
        {
            return testAgainst < scriptObjectRef.TestFloat;
        }
        
        public override void Init(UnityEngine.ScriptableObject so)
        {
            this.scriptObjectRef = ((VariableTester)(so));
        }
    }
}
